### ISSUE TITLE
voting authority does not enforce that authorities cast the same vote to all authorities.

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/authority#22]
as implemented AND specified, a malicious authority could cast a different vote to different sets of authorities to split the consensus.

consider n authorities, of which 1 is malicious.
consensus is defined as n/2 + 1 votes
the malicious authority sends half of the other authorities each a different vote, perhaps with a different mix descriptor.
each authority will combine the votes they have received from the other authorities, and send its signature of the combined votes to the other peers.
then, two sets of n/2 - 1 authorities will each receive n/2 -1 signatures for a document they do not have, and n/2 signatures for a document that they do have, and each set of authorities will publish a different consensus.

Should the authorities detect "alternate consensus" above a threshold and do something? What if there are more malicious authorities - how should such a threshold value be determined? According to https://github.com/katzenpost/docs/blob/master/specs/pki.rst#13-security-properties-overview
"All Directory Authority servers must agree with each other on the set of mixes." We probably want to tolerate downtime or network failure/partition - perhaps we should amend the specification to state that the consensus will fail if less than a consensus threshold of directory authorities agree with each other on the set of mixes, or if more than m other directory authorities agree on an alternate consensus.

Currently consensus threshold is 2/n + 1. Should we use something else here?

or, should the voting protocol be changed to implement paxos: https://lamport.azurewebsites.net/pubs/paxos-simple.pdf

**Comment by david415** [comment]
* yes, our designs as specified are very intentionally NOT byzantine fault tolerant.
* it's true that the system could have a protocol extension for detecting the reason for voting failure.
* "All Directory Authority servers must agree with each other on the set of mixes."; you take that to mean the system doesn't tolerate downtime? hmm I see what you mean... but I think it's NOT the set of mixes that uploaded descriptors lately.... but instead means the set of mixes that we know about even if we don't receive anything from them.
* paxos completeness sounds good until you realize it implies a voting round could perhaps take forever. anyway, the answer is that someone should do some real research a design a better system; if we like what they've designed then we'll implement it. but not now because our design is almost fully implemented and is therefore less work to complete.
